name: Organization Issue Bot

on:
  issues:
    types:
      - opened

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue contains specific text
        id: check_text
        run: |
          if [[ "${{ github.event.issue.body }}" == *"This is my new organization"* ]]; then
            echo "::set-output name=triggered::true"
          fi

      - name: Create new branch
        id: create_branch
        if: steps.check_text.outputs.triggered
        run: |
          branch_number=$(git ls-remote origin | grep -c "refs/heads/neworganization-")
          new_branch="new-$(printf "%04d" $(( branch_number + 1 )))"
          git checkout -b $new_branch
          echo "::set-output name=new_branch::${new_branch}"

      - name: Upload files
        if: steps.create_branch.outputs.new_branch
        run: |
          # 上传你的文件到新分支

      - name: Open Pull Request
        if: steps.create_branch.outputs.new_branch
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.create_branch.outputs.new_branch }}
          title: "Organization：New organization of"
          body: "New branch and pull request automatically created."
          labels: "组织/Organization"
